version: '3'
services:

  db:
    container_name: mysql_db
    restart: always
    image: mysql:8.0.2
    ports:
      - "3360:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${RPASS}
      MYSQL_HOST: ${HOST}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${UPASS}
      MYSQL_DB: ${DBNAME}
    volumes:
      - "./data:/var/lib/mysql:rw"
    networks:
      static_ip:
        ipv4_address: 198.168.1.1

  goweb:
    build: ./backend/users
    image: users
    container_name: go-user-test
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      static_ip:
        ipv4_address: 198.168.1.2

networks:
  static_ip:
    ipam:
      driver: default
      config:
        - subnet: 198.168.0.0/20
