version: '3'
services:
  goapi:
    build: .
    image: temp
    container_name: user-testing
    restart: always
    ports:
      - "8080:8080"
    networks:
      static_ip:
        ipv4_address: 198.168.1.2
  db:
    image: mysql:8.0.2
    container_name: app-db
    restart: always
    ports:
      - "3360:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${RPASS}
      MYSQL_HOST: ${HOST}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${UPASS}
      MYSQL_DATABASE: ${DBNAME}
    volumes:
      - "./data:/var/lib/mysql:rw"
    networks:
      static_ip:
        ipv4_address: 198.168.1.3

networks:
  static_ip:
    ipam:
      driver: default
      config:
        - subnet: 198.168.0.0/20
